#!/bin/bash

############################################
# This script has the logic for building a
# Docker image based on the Dockerfile.
############################################

tmpDir=/tmp/TidyGEO_build

rm -rf $tmpDir
mkdir -p $tmpDir

cp Dockerfile $tmpDir/
cp -r TidyGEO/* $tmpDir/

cd $tmpDir
docker build -t srp33/tidygeo:v$(cat VERSION) .
cd -
