#!/bin/bash

############################################
# This script has the logic for building a
# Docker image based on the Dockerfile.
############################################

set -o errexit

tmpDir=/tmp/TidyGEO_build_${USER}

rm -rf $tmpDir
mkdir -p $tmpDir

cp Dockerfile $tmpDir/
cp -r TidyGEO/* $tmpDir/

pushd $tmpDir
if [ $(arch) = "arm64" ]; then
    docker buildx build --platform linux/arm64 -t srp33/tidygeo:v$(cat VERSION) .
else
    docker build -t srp33/tidygeo:v$(cat VERSION) .
fi
popd
