#!/bin/bash

######################################################
# This script has the logic for executing
# Good Nomen within a Docker container after
# the Docker image has been created.
# It will run on port 8080.
# It should be accessible from a browser at
#   http://localhost:8080/GoodNomen
# You must have an API key for BioPortal in
#   this directory when you execute this script.
#   This file should be called BioPortalApiKey.txt.
#######################################################

set -o errexit

# First stop the container if it is currently running.
./stop_docker

# Then rebuild the container image using the latest code.
./build_docker

# Now execute the container in interactive mode.
# Hit Ctrl-C when you want to close the container.
docker run --rm -i -t --name tidygeo -p 8080:3838 \
    srp33/tidygeo:v$(cat TidyGEO/VERSION)
