#!/bin/bash

if [ $( docker ps -a | grep tidygeo | wc -l ) -gt 0 ]; then
  echo "A tidygeo container is currently running and will now be stopped."

  # This will stop the container when it is running in detached mode.
  docker container stop tidygeo
fi
