tabPanel(title = icon("exchange-alt"), value = "1", 
         h4("Matching up datasets"),
         p(paste("Here is where you can make sure the assay data only includes the samples listed",
                  "in the clinical data (and visa versa) and the assay data only has the probes listed in the",
                  "feature data (and visa versa). Please note that this will not combine any of these datasets,",
                  "only filter the rows so that the data is concordant.")),
         selectInput("data_to_match1", "Choose the first dataset to match:", choices = c("clinical", "assay", "feature")),
         uiOutput("col_to_match1_selector"),
         selectInput("data_to_match2", "Choose the second dataset to match:", choices = c("clinical", "assay", "feature")),
         uiOutput("col_to_match2_selector"),
         primary_button("match_columns", div(icon("exchange-alt"), "Match")),
         undo_button("undo_match"),
         hr(), tertiary_button("all_to_assay_button", div(icon("arrow-left"), "Back to assay")),
         secondary_button("all_1_to_2_button", div("Next", icon("arrow-right")), class = "right_align")
)